Add few simply reply
LittleSkinCommspt/commspt-bot pull request #19
Opened 2021-08-05 13:23 UTC by Nofated095

- &dns
- &launcher
- &pw
- &log.minecraft
- &log.launcher

2021-08-05 13:40 UTC, jinzhijie commented on texts.py
> +    log_minecraft = '我们需要根据你的游戏日志对问题进行判断，一般日志文件存放在 .minecraft/versions/log/latest.log'
请使用启动器的「测试游戏」功能启动游戏，并在复现问题后导出日志发送至群内。如果问题与外置登录有关，请在启动器的「 JVM 参数」设置中填入 -Dauthlibinjector.debug

2021-08-05 13:40 UTC, jinzhijie commented on texts.py
> +    log_launcher = '我们需要根据你的启动器日志对问题进行判断，一般情况下你可以在设置中导出启动器日志'
请在启动器中复现你的问题，然后导出启动器日志发送至群内

2021-08-05 13:41 UTC, jinzhijie requested changes
dns launcher email change_password 不要  
那两个改一下

2021-08-05 15:48 UTC, Mashirl commented
ping @jinzhijie

2021-08-05 16:15 UTC, Mashirl commented
Maybe we need a "&log" command to send both messages. @jinzhijie

2021-08-05 23:26 UTC, jinzhijie approved these changes

2021-08-05 23:27 UTC, jinzhijie commented
Why we need it? What should it do?

2021-08-06 00:36 UTC, Cubik65536 commented
> Why we need it? What should it do?

确实有些人不知道怎么找到log

2021-08-06 01:08 UTC, Nofated095 commented
Thanks

2021-08-07 02:52 UTC, merged