Update main.py
LittleSkinCommspt/commspt-bot pull request #2
Opened 2020-08-11 11:30 UTC by Restent

啊我去你妈的腾讯

2020-08-12 02:27 UTC, SerinaNya requested changes
语法错误还不改？

2020-08-12 08:34 UTC, Restent commented
改好了 自己再看一次

2020-08-12 08:40 UTC, Restent commented
> 语法错误还不改？

改了 自己看 @jinzhijie

2020-08-13 03:00 UTC, SerinaNya approved these changes
行

2020-08-13 03:02 UTC, jinzhijie commented
我手机出了点问题，你自己 Merge 一下（

2020-08-14 01:30 UTC, merged