Rewrite some text
LittleSkinCommspt/commspt-bot pull request #43
Opened 2023-04-14 07:28 UTC by SliverRiver327

文案后遗症（不是

2023-04-14 15:43 UTC, Cubik65536 approved these changes
还… 行？不知道这些更改是否真的非常必要

2023-04-17 01:56 UTC, SliverRiver327 commented
> 还… 行？不知道这些更改是否真的非常必要

其实 CSL GUI 那个都可以删了，应该没人用这个东西了吧...

2023-04-17 07:12 UTC, FLYEMOJ1 requested changes
**个人觉得只有Ping不需要改动。**
LGFM!

2023-04-17 07:12 UTC, FLYEMOJ1 commented on texts.py
> +    ping = '你好*N'
推荐保持原样。
更有Minecraft的味道（x

2023-04-17 10:28 UTC, Nofated095 approved these changes

2023-04-17 10:38 UTC, FLYEMOJ1 approved these changes

2023-04-17 10:39 UTC, FLYEMOJ1 commented
LGMF

2023-04-17 10:40 UTC, FLYEMOJ1 commented
@SliverRiver327 
确认完了 允许Merge

2023-04-17 10:40 UTC, merged