New command `&java.latest`
LittleSkinCommspt/commspt-bot pull request #44
Opened 2023-06-20 14:42 UTC by bingling-sama

2023-06-20 15:01 UTC, SerinaNya requested changes

2023-06-20 15:01 UTC, jinzhijie commented on models/apis.py
> +    return r.text
- 返回值需要拼接成官网域名的文件下载 URL
- 需要将 query params 单独以 dict 的形式传给 httpx
- 此版本代码中存在 bug，字符串无法被正确格式化

2023-06-20 15:04 UTC, SerinaNya commented on models/apis.py
> +    return r.text
补充：

需要使用异步调用，请将其改为 async 版本。

<https://www.python-httpx.org/async/>

2023-06-20 23:56 UTC, jinzhijie requested changes

2023-06-20 23:56 UTC, jinzhijie commented on models/apis.py
> +        return url
- 删除 L162
- L163 向左取消一个缩进

这是 with 捏。 。

2023-06-20 23:56 UTC, jinzhijie commented on modules/latest_versions.py
> +    url = getLiberica(version, type)
无法运行的代码：调用异步函数需要使用 await 关键字捏

2023-06-21 04:36 UTC, jinzhijie requested changes

2023-06-21 04:36 UTC, jinzhijie commented on modules/latest_versions.py
> +@channel.use(CommandSchema('&java.latest {type: str = "jre"} {version: int = "8"}'))
type 和 version 顺序换一下吧

2023-06-21 05:39 UTC, bingling-sama commented on modules/latest_versions.py
> +@channel.use(CommandSchema('&java.latest {type: str = "jre"} {version: int = "8"}'))
好的，不过这个命令解析器不会根据输入参数类型判断是哪个参数吗？

2023-06-21 10:17 UTC, jinzhijie approved these changes

2023-06-21 10:17 UTC, merged